namespace UnrealReplayReader.Fortnite.Models.Enums;

public enum EAthenaTravelEventType : byte
{
    GroundMove = 0,
    AirMove = 1,
    BattleBusJump = 2,
    LaunchJump = 3,
    Landed = 4,
    OpenChest = 5,
    OpenAmmo = 6,
    GotAssist = 7,
    GotKnockdown = 8,
    GotKill = 9,
    PlayerDowned = 10,
    PlayerDied = 11,
    Won = 12,
    DealtDamage = 13,
    HealthChange = 14,
    GotItem = 15,
    DroppedItem = 16,
    ShieldChange = 17,
    WeaponExecuted = 18,
    EnteredVehicle = 19,
    ExitedVehicle = 20,
    TrapBuilt = 21,
    UsedItem = 22,
    ZoneUpdate = 23,
    PlacedBuilding = 24,
    EmoteUsed = 25,
    UpgradedBuilding = 26,
    EditedBuilding = 27,
    Count = 28,
    EAthenaTravelEventTypeMax = 29
}